### ISSUE TITLE
error with run.bat (look at desc)

### ISSUE THREAD

**Issue by kamilthecitratester** [sticks-stuff/CPSC#88]
07:26:28 [Info] > Loaded 1 plugin(s): LoginNotice
07:26:28 [Fine] > Login server is online
PHP Fatal error:  Uncaught Error: Call to undefined function Kitsune\socket_create() in C:\xampp\htdocs\Kitsune\Spirit.php:50
Stack trace:
#0 C:\xampp\htdocs\Run.php(36): Kitsune\Spirit->listen(Object(SimpleXMLElement), 6112)
#1 {main}
  thrown in C:\xampp\htdocs\Kitsune\Spirit.php on line 50

Fatal error: Uncaught Error: Call to undefined function Kitsune\socket_create() in C:\xampp\htdocs\Kitsune\Spirit.php:50
Stack trace:
#0 C:\xampp\htdocs\Run.php(36): Kitsune\Spirit->listen(Object(SimpleXMLElement), 6112)
#1 {main}
  thrown in C:\xampp\htdocs\Kitsune\Spirit.php on line 50
Press any key to continue . . .

**Comment by kamilthecitratester** [comment]
thats the error @everyone

**Comment by kamilthecitratester** [comment]
thats the error

**Comment by kamilthecitratester** [comment]
nmv

**Comment by kamilthecitratester** [comment]
dc
